"""
Report Generation Module.

This module generates incident reports for detected anomalies using
Jinja2 templates. Reports include:

1. Summary of what happened
2. KPI trend description with numbers
3. Severity and impact assessment
4. Top suspected drivers (hierarchical)
5. Calendar context (events/SNAP)
6. Recommended next checks (rule-based)

Output: Markdown reports in outputs/reports/
"""

import logging
import sys
from pathlib import Path
from typing import Dict, List, Optional
from datetime import datetime

import pandas as pd
from jinja2 import Environment, BaseLoader

sys.path.insert(0, str(Path(__file__).parent.parent))

from src.config import (
    DATA_PROCESSED,
    OUTPUTS_REPORTS,
    ANOMALIES_FILE,
    RCA_DRIVERS_FILE,
    METRIC_FACTS_FILE,
)
from src.utils import setup_logger, format_number, format_percentage

logger = setup_logger(__name__)


# Jinja2 template for incident reports
REPORT_TEMPLATE = """# Incident Report: {{ event_id }}

**Generated:** {{ generated_at }}

---

## 1. Summary

{{ summary }}

---

## 2. Event Details

| Field | Value |
|-------|-------|
| Event ID | {{ event_id }} |
| Metric | {{ metric_name }} |
| Level | {{ level }} |
| Segment | {{ segment_key }} |
| Start Date | {{ start_date }} |
| End Date | {{ end_date }} |
| Duration | {{ duration_days }} day(s) |
| Peak Date | {{ peak_date }} |
| Direction | {{ direction }} |

---

## 3. KPI Trend and Impact

### Observed Values

| Measure | Value |
|---------|-------|
| Value at Peak | {{ value_peak }} |
| Expected Baseline | {{ baseline_peak }} |
| Absolute Change | {{ absolute_change }} |
| Percentage Change | {{ pct_change }} |

### Severity Assessment

| Severity Type | Score |
|---------------|-------|
| Z-Score Severity | {{ z_severity }} / 100 |
| Percentage Severity | {{ pct_severity }} / 100 |

**Impact Level:** {{ impact_level }}

---

## 4. Top Suspected Drivers

{% if drivers %}
The following segments showed the largest contribution to this anomaly:

| Rank | Segment | Before | After | Delta | Share Change | Score |
|------|---------|--------|-------|-------|--------------|-------|
{% for driver in drivers %}
| {{ driver.rank }} | {{ driver.child_segment_key }} | {{ driver.child_before }} | {{ driver.child_after }} | {{ driver.delta_value }} | {{ driver.delta_share }} | {{ driver.driver_score }} |
{% endfor %}

{% if top_driver_insight %}
**Key Insight:** {{ top_driver_insight }}
{% endif %}
{% else %}
No child-level drivers identified for this event.
{% endif %}

---

## 5. Calendar Context

| Context | Value |
|---------|-------|
| Day of Week | {{ weekday }} |
| Weekend | {{ is_weekend }} |
| Event | {{ event_name }} |
| Event Type | {{ event_type }} |
| SNAP Active | {{ snap_flag }} |

{% if calendar_insight %}
**Calendar Note:** {{ calendar_insight }}
{% endif %}

---

## 6. Recommended Next Checks

Based on the anomaly characteristics, consider the following investigation steps:

{% for check in recommended_checks %}
- {{ check }}
{% endfor %}

---

## 7. Technical Details

```
Anomaly Detection Parameters:
- STL Period: 7 (weekly seasonality)
- MAD Window: 28 days
- Z-Score Threshold: 3.5
- Cooldown Period: 2 days
- Before Window: 28 days
```

---

*Report generated by KPI Sentinel*
"""


def get_recommended_checks(
    metric_name: str,
    direction: str,
    drivers: List[Dict],
    calendar_context: Dict
) -> List[str]:
    """
    Generate rule-based recommended next checks.
    
    Args:
        metric_name: The anomaly metric name.
        direction: Anomaly direction (spike/drop).
        drivers: List of top drivers.
        calendar_context: Calendar context dictionary.
    
    Returns:
        List of recommended check strings.
    """
    checks = []
    
    # Metric-specific checks
    if metric_name == "revenue":
        if direction == "drop":
            checks.append("Investigate demand/supply disruption: Check inventory levels and fulfillment rates")
            checks.append("Review top store/department drivers for localized issues")
            checks.append("Compare with units metric to determine if volume or price driven")
        else:
            checks.append("Verify if revenue spike is sustainable or one-time event")
            checks.append("Check for promotional activities or pricing changes")
    
    elif metric_name == "units":
        if direction == "drop":
            checks.append("Check for stockout conditions across affected segments")
            checks.append("Review supply chain status and delivery schedules")
            checks.append("Investigate competitor activity or market shifts")
        else:
            checks.append("Verify inventory can sustain increased demand")
            checks.append("Check for promotional or marketing campaign effects")
    
    elif metric_name == "avg_price":
        if direction == "spike":
            checks.append("Inspect sell_price changes by store/item in the prices table")
            checks.append("Check for product mix shifts toward higher-priced items")
            checks.append("Review pricing policy changes or competitor pricing")
        else:
            checks.append("Check for promotional discounts or clearance activities")
            checks.append("Investigate product mix shifts toward lower-priced items")
    
    elif metric_name == "zero_sales_rate":
        if direction == "spike":
            checks.append("Potential stockout detected: Check which stores/departments have highest zero share")
            checks.append("Review inventory replenishment schedules")
            checks.append("Investigate supply chain bottlenecks")
        else:
            checks.append("Improved availability: Verify inventory levels are adequate")
    
    elif metric_name == "price_index":
        checks.append("Review pricing strategy relative to historical patterns")
        checks.append("Check for seasonal pricing adjustments")
    
    elif metric_name == "demand_volatility":
        if direction == "spike":
            checks.append("Investigate causes of demand instability")
            checks.append("Review forecasting accuracy for affected segments")
        else:
            checks.append("Demand stabilizing: Monitor for sustained improvement")
    
    # Calendar-based checks
    if calendar_context.get("event_name"):
        checks.append(f"Consider impact of calendar event: {calendar_context['event_name']}")
    
    if calendar_context.get("snap_flag"):
        checks.append("SNAP benefits active: Factor in government assistance program effects")
    
    if calendar_context.get("is_weekend"):
        checks.append("Weekend pattern: Compare with typical weekend behavior")
    
    # Driver-based checks
    if drivers:
        top_driver = drivers[0]
        checks.append(f"Deep-dive into top driver: {top_driver['child_segment_key']}")
    
    return checks


def get_impact_level(z_severity: float, pct_severity: float) -> str:
    """
    Determine impact level based on severity scores.
    
    Args:
        z_severity: Z-score based severity (0-100).
        pct_severity: Percentage based severity (0-100).
    
    Returns:
        Impact level string.
    """
    avg_severity = (z_severity + pct_severity) / 2
    
    if avg_severity >= 80:
        return "CRITICAL"
    elif avg_severity >= 60:
        return "HIGH"
    elif avg_severity >= 40:
        return "MEDIUM"
    else:
        return "LOW"


def generate_summary(event: pd.Series, drivers: List[Dict]) -> str:
    """
    Generate a natural language summary of the anomaly.
    
    Args:
        event: Event row from anomalies DataFrame.
        drivers: List of top drivers.
    
    Returns:
        Summary string.
    """
    metric = event["metric_name"]
    direction = event["direction"]
    level = event["level"]
    segment = event["segment_key"]
    pct_change = event.get("pct_change_peak", 0)
    duration = event.get("duration_days", 1)
    
    direction_word = "increased" if direction == "spike" else "decreased"
    
    summary = (
        f"A significant {direction} in **{metric}** was detected at the **{level}** level "
        f"for segment **{segment}**. "
        f"The metric {direction_word} by approximately **{abs(pct_change)*100:.1f}%** "
        f"from the expected baseline. "
        f"This anomaly persisted for **{duration} day(s)**."
    )
    
    if drivers:
        top_driver = drivers[0]["child_segment_key"]
        summary += f" The primary contributing segment was **{top_driver}**."
    
    return summary


def generate_top_driver_insight(
    metric_name: str,
    drivers: List[Dict],
    direction: str
) -> Optional[str]:
    """
    Generate insight about the top driver.
    
    Args:
        metric_name: The anomaly metric name.
        drivers: List of top drivers.
        direction: Anomaly direction.
    
    Returns:
        Insight string or None.
    """
    if not drivers:
        return None
    
    top = drivers[0]
    segment = top["child_segment_key"]
    delta_share = top.get("delta_share", 0)
    
    if abs(delta_share) > 0.1:
        if delta_share > 0:
            return f"{segment} significantly increased its share of total {metric_name}, suggesting localized growth or shift."
        else:
            return f"{segment} significantly decreased its share of total {metric_name}, suggesting localized decline or shift."
    
    # For avg_price, check decomposition
    if metric_name == "avg_price" and "price_decomp_hint" in top:
        hint = top["price_decomp_hint"]
        return f"Price change primarily driven by {hint} changes rather than the other component."
    
    return None


def generate_calendar_insight(calendar_context: Dict) -> Optional[str]:
    """
    Generate insight about calendar context.
    
    Args:
        calendar_context: Calendar context dictionary.
    
    Returns:
        Insight string or None.
    """
    insights = []
    
    if calendar_context.get("event_name"):
        insights.append(f"A calendar event ({calendar_context['event_name']}) occurred on this date, which may have influenced the metric.")
    
    if calendar_context.get("snap_flag"):
        insights.append("SNAP benefits were active, potentially affecting consumer purchasing behavior.")
    
    if calendar_context.get("is_weekend"):
        insights.append("This occurred on a weekend, which typically shows different shopping patterns.")
    
    return " ".join(insights) if insights else None


def generate_report(
    event_id: str,
    anomalies: Optional[pd.DataFrame] = None,
    rca_drivers: Optional[pd.DataFrame] = None,
    output_dir: Optional[Path] = None
) -> str:
    """
    Generate an incident report for a specific event.
    
    Args:
        event_id: The event ID to generate report for.
        anomalies: Optional anomalies DataFrame.
        rca_drivers: Optional RCA drivers DataFrame.
        output_dir: Optional output directory.
    
    Returns:
        Generated report as markdown string.
    """
    # Load data if not provided
    if anomalies is None:
        anomalies = pd.read_parquet(DATA_PROCESSED / ANOMALIES_FILE)
    
    if rca_drivers is None:
        rca_path = DATA_PROCESSED / RCA_DRIVERS_FILE
        if rca_path.exists():
            rca_drivers = pd.read_parquet(rca_path)
        else:
            rca_drivers = pd.DataFrame()
    
    # Get event
    event = anomalies[anomalies["event_id"] == event_id]
    if len(event) == 0:
        raise ValueError(f"Event {event_id} not found")
    event = event.iloc[0]
    
    # Get drivers for this event
    if len(rca_drivers) > 0 and "event_id" in rca_drivers.columns:
        drivers = rca_drivers[rca_drivers["event_id"] == event_id].to_dict("records")
        drivers = sorted(drivers, key=lambda x: x.get("rank", 999))[:10]  # Top 10
    else:
        drivers = []
    
    # Extract calendar context from drivers or use defaults
    calendar_context = {
        "weekday": drivers[0].get("weekday", "Unknown") if drivers else "Unknown",
        "is_weekend": drivers[0].get("is_weekend", False) if drivers else False,
        "event_name": drivers[0].get("event_name", None) if drivers else None,
        "event_type": drivers[0].get("event_type", None) if drivers else None,
        "snap_flag": drivers[0].get("snap_flag", None) if drivers else None,
    }
    
    # Generate components
    summary = generate_summary(event, drivers)
    recommended_checks = get_recommended_checks(
        event["metric_name"],
        event["direction"],
        drivers,
        calendar_context
    )
    impact_level = get_impact_level(
        event.get("z_severity_peak", 0),
        event.get("pct_severity_peak", 0)
    )
    top_driver_insight = generate_top_driver_insight(
        event["metric_name"],
        drivers,
        event["direction"]
    )
    calendar_insight = generate_calendar_insight(calendar_context)
    
    # Format driver values for display
    formatted_drivers = []
    for d in drivers:
        formatted_drivers.append({
            "rank": d.get("rank", "-"),
            "child_segment_key": d.get("child_segment_key", "-"),
            "child_before": format_number(d.get("child_before", 0)),
            "child_after": format_number(d.get("child_after", 0)),
            "delta_value": format_number(d.get("delta_value", 0)),
            "delta_share": format_percentage(d.get("delta_share", 0)),
            "driver_score": format_number(d.get("driver_score", 0)),
        })
    
    # Prepare template context
    context = {
        "event_id": event_id,
        "generated_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "metric_name": event["metric_name"],
        "level": event["level"],
        "segment_key": event["segment_key"],
        "start_date": str(event.get("start_date", "-")),
        "end_date": str(event.get("end_date", "-")),
        "duration_days": event.get("duration_days", 1),
        "peak_date": str(event.get("peak_date", "-")),
        "direction": event["direction"],
        "value_peak": format_number(event.get("value_peak", 0)),
        "baseline_peak": format_number(event.get("baseline_peak", 0)),
        "absolute_change": format_number(
            event.get("value_peak", 0) - event.get("baseline_peak", 0)
        ),
        "pct_change": format_percentage(event.get("pct_change_peak", 0)),
        "z_severity": f"{event.get('z_severity_peak', 0):.1f}",
        "pct_severity": f"{event.get('pct_severity_peak', 0):.1f}",
        "impact_level": impact_level,
        "summary": summary,
        "drivers": formatted_drivers,
        "top_driver_insight": top_driver_insight,
        "weekday": calendar_context["weekday"],
        "is_weekend": "Yes" if calendar_context["is_weekend"] else "No",
        "event_name": calendar_context["event_name"] or "None",
        "event_type": calendar_context["event_type"] or "None",
        "snap_flag": "Yes" if calendar_context["snap_flag"] else "No",
        "calendar_insight": calendar_insight,
        "recommended_checks": recommended_checks,
    }
    
    # Render template
    env = Environment(loader=BaseLoader())
    template = env.from_string(REPORT_TEMPLATE)
    report = template.render(**context)
    
    # Save report
    if output_dir is None:
        output_dir = OUTPUTS_REPORTS
    output_dir.mkdir(parents=True, exist_ok=True)
    
    output_path = output_dir / f"event_{event_id}.md"
    with open(output_path, "w") as f:
        f.write(report)
    
    logger.info(f"Report saved to {output_path}")
    
    return report


def generate_all_reports(
    anomalies: Optional[pd.DataFrame] = None,
    rca_drivers: Optional[pd.DataFrame] = None,
    max_reports: int = 50
) -> List[str]:
    """
    Generate reports for all anomaly events.
    
    Args:
        anomalies: Optional anomalies DataFrame.
        rca_drivers: Optional RCA drivers DataFrame.
        max_reports: Maximum number of reports to generate.
    
    Returns:
        List of generated report paths.
    """
    # Load data if not provided
    if anomalies is None:
        anomalies = pd.read_parquet(DATA_PROCESSED / ANOMALIES_FILE)
    
    if rca_drivers is None:
        rca_path = DATA_PROCESSED / RCA_DRIVERS_FILE
        if rca_path.exists():
            rca_drivers = pd.read_parquet(rca_path)
        else:
            rca_drivers = pd.DataFrame()
    
    # Sort by severity and take top events
    if "z_severity_peak" in anomalies.columns:
        anomalies = anomalies.sort_values("z_severity_peak", ascending=False)
    
    event_ids = anomalies["event_id"].head(max_reports).tolist()
    
    report_paths = []
    for event_id in event_ids:
        try:
            generate_report(event_id, anomalies, rca_drivers)
            report_paths.append(str(OUTPUTS_REPORTS / f"event_{event_id}.md"))
        except Exception as e:
            logger.error(f"Failed to generate report for {event_id}: {e}")
    
    logger.info(f"Generated {len(report_paths)} reports")
    return report_paths


def main():
    """Main entry point for the report module."""
    try:
        generate_all_reports()
    except FileNotFoundError as e:
        logger.error(str(e))
        sys.exit(1)
    except Exception as e:
        logger.exception(f"Report generation failed: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
